apiVersion: v1
kind: Service
metadata:
  namespace: librum-ci
  name: librum-ci-githooks
  labels:
    name: librum-ci-githooks
    visualize: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9001
      protocol: TCP
  selector:
    name: librum-ci-githooks
