apiVersion: v1
kind: Service
metadata:
  namespace: librum-ci
  name: librum-ci-master
  labels:
    name: librum-ci-master
    visualize: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: librum-ci-master
